AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  A simple backend (read/write to DynamoDB) with a RESTful API endpoint using
  Amazon API Gateway.
Resources:
  legocatalog:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: lego-catalog-backend
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: >-
        Testing to update lambda function
      MemorySize: 512
      Timeout: 10
      Role: 'arn:aws:iam::526200438718:role/service-role/microservices-lambda'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /set
            Method: ANY
      Environment:
        Variables:
          TableName: lego-catalog
      Tags:
        'lambda-console:blueprint': microservice-http-endpoint
